runtime: nodejs20
# instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

#  handlers:
#    - url: /.*
#     secure: always
#     redirect_http_response_code: 301
#     script: auto
#     expiration: "0d 0h"
# - url: /stylesheets
#   static_dir: stylesheets

